# Generated by Django 4.2.7 on 2025-10-31 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('primary', 'Primary'), ('backup', 'Backup'), ('specialist', 'Specialist')], default='primary', max_length=20, verbose_name='assignment type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='status')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('estimated_arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='estimated arrival time')),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='actual arrival time')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'incident assignment',
                'verbose_name_plural': 'incident assignments',
                'db_table': 'incident_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponderChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_role', models.CharField(help_text='Role this checklist applies to', max_length=30, verbose_name='responder role')),
                ('checklist_items', models.JSONField(default=list, help_text='List of checklist items with order, description, required', verbose_name='checklist items')),
                ('is_required', models.BooleanField(default=True, verbose_name='is required')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'responder checklist',
                'verbose_name_plural': 'responder checklists',
                'db_table': 'responder_checklists',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResponderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='accuracy (meters)')),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='speed (km/h)')),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='heading (degrees)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('device_id', models.CharField(blank=True, max_length=100, verbose_name='device ID')),
            ],
            options={
                'verbose_name': 'responder location',
                'verbose_name_plural': 'responder locations',
                'db_table': 'responder_locations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ResponseMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('on_scene', 'On Scene'), ('transporting', 'Transporting'), ('cleared', 'Cleared')], max_length=20, verbose_name='milestone type')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('media_attachments', models.JSONField(blank=True, default=list, verbose_name='media attachments')),
                ('milestone_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='milestone hash')),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='blockchain transaction hash')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='response.incidentassignment')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'response milestone',
                'verbose_name_plural': 'response milestones',
                'db_table': 'response_milestones',
                'ordering': ['-timestamp'],
            },
        ),
    ]
