# Generated by Django 4.2.7 on 2025-10-31 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsemilestone',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responderlocation',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responderchecklist',
            name='incident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='incidents.incidenttype'),
        ),
        migrations.AddField(
            model_name='incidentassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentassignment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='incidents.incident'),
        ),
        migrations.AddIndex(
            model_name='responderlocation',
            index=models.Index(fields=['responder', '-timestamp'], name='responder_l_respond_5a1753_idx'),
        ),
        migrations.AddIndex(
            model_name='responderlocation',
            index=models.Index(fields=['is_active', 'timestamp'], name='responder_l_is_acti_b0a567_idx'),
        ),
    ]
