# Generated by Django 4.2.7 on 2025-10-31 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentvalidation',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cctvfeed',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='iot.cctvcamera'),
        ),
        migrations.AddField(
            model_name='cctvfeed',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cctv_feeds', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='cctvfeed',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['timestamp', 'sensor'], name='sensor_read_timesta_a410e5_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['sensor', 'anomaly_detected'], name='sensor_read_sensor__23aeb2_idx'),
        ),
        migrations.AddIndex(
            model_name='rfidlog',
            index=models.Index(fields=['timestamp', 'reader'], name='rfid_logs_timesta_a5902f_idx'),
        ),
        migrations.AddIndex(
            model_name='rfidlog',
            index=models.Index(fields=['vehicle_tag', 'timestamp'], name='rfid_logs_vehicle_959e7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incidentvalidation',
            unique_together={('incident', 'validation_source')},
        ),
    ]
