# Generated by Django 4.2.7 on 2025-10-31 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('verification', 'Verification'), ('qa', 'Quality Assurance'), ('audit', 'Audit')], default='verification', max_length=20, verbose_name='review type')),
                ('review_status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='review status')),
                ('review_notes', models.TextField(blank=True, verbose_name='review notes')),
                ('review_duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='review duration (seconds)')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='reviewed at')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_reviews', to='incidents.incident')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'human review',
                'verbose_name_plural': 'human reviews',
                'db_table': 'human_reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='AIVerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(default='v1.0', max_length=50, verbose_name='model version')),
                ('model_name', models.CharField(default='YOLOv8', max_length=100, verbose_name='model name')),
                ('classification_result', models.CharField(choices=[('accident', 'Accident'), ('hazard', 'Hazard'), ('obstruction', 'Obstruction'), ('vandalism', 'Vandalism'), ('false', 'False Report'), ('unknown', 'Unknown')], max_length=50, verbose_name='classification')),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='0-100% confidence', max_digits=5, verbose_name='confidence score')),
                ('duplicate_detection_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='duplicate detection score')),
                ('credibility_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='credibility score')),
                ('processing_time', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='processing time (seconds)')),
                ('model_metadata', models.JSONField(blank=True, default=dict, help_text='Additional model-specific metadata', verbose_name='model metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'AI verification result',
                'verbose_name_plural': 'AI verification results',
                'db_table': 'ai_verification_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
