# Generated by Django 4.2.7 on 2025-10-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='action type')),
                ('entity_type', models.CharField(max_length=50, verbose_name='entity type')),
                ('entity_id', models.CharField(max_length=100, verbose_name='entity ID')),
                ('action_details', models.JSONField(default=dict, verbose_name='action details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('blockchain_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='blockchain hash')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
