# Generated by Django 4.2.7 on 2025-10-31 09:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='incident ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('false', 'False Report')], default='pending', max_length=20, verbose_name='status')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='anonymous report')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='description')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('road_classification', models.CharField(blank=True, max_length=50, verbose_name='road classification')),
                ('road_name', models.CharField(blank=True, max_length=200, verbose_name='road name')),
                ('nearest_milestone', models.CharField(blank=True, max_length=100, verbose_name='nearest milestone')),
                ('timestamp', models.DateTimeField(verbose_name='incident timestamp')),
                ('weather', models.CharField(blank=True, max_length=50, verbose_name='weather')),
                ('lane_count', models.IntegerField(blank=True, null=True, verbose_name='lane count')),
                ('vehicles_involved_count', models.IntegerField(default=0, verbose_name='vehicles involved')),
                ('has_injuries', models.BooleanField(default=False, verbose_name='has injuries')),
                ('infrastructure_damage_tags', models.JSONField(blank=True, default=list, verbose_name='infrastructure damage tags')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('false', 'False')], default='pending', max_length=20, verbose_name='verification status')),
                ('ai_confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='0-100', max_digits=5, null=True, verbose_name='AI confidence score')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('is_duplicate', models.BooleanField(default=False, verbose_name='is duplicate')),
                ('sla_start_time', models.DateTimeField(blank=True, null=True, verbose_name='SLA start time')),
                ('sla_target_time', models.DateTimeField(blank=True, null=True, verbose_name='SLA target time')),
                ('sla_breach_time', models.DateTimeField(blank=True, null=True, verbose_name='SLA breach time')),
                ('escalation_level', models.IntegerField(default=0, verbose_name='escalation level')),
                ('incident_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='incident hash')),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='blockchain transaction hash')),
                ('blockchain_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='blockchain timestamp')),
                ('blockchain_block_number', models.BigIntegerField(blank=True, null=True, verbose_name='blockchain block number')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='resolution notes')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'incident',
                'verbose_name_plural': 'incidents',
                'db_table': 'incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='comment')),
                ('comment_type', models.CharField(choices=[('internal', 'Internal'), ('public', 'Public')], default='internal', max_length=20, verbose_name='comment type')),
                ('is_edited', models.BooleanField(default=False, verbose_name='is edited')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='edited at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'incident comment',
                'verbose_name_plural': 'incident comments',
                'db_table': 'incident_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentSeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10, unique=True, verbose_name='severity level')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('response_time_target_minutes', models.IntegerField(verbose_name='response time target (minutes)')),
                ('escalation_time_minutes', models.IntegerField(verbose_name='escalation time (minutes)')),
                ('color_code', models.CharField(default='#FF0000', max_length=7, verbose_name='color code')),
                ('priority_score', models.IntegerField(help_text='Higher = more priority', verbose_name='priority score')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'incident severity',
                'verbose_name_plural': 'incident severities',
                'db_table': 'incident_severities',
                'ordering': ['priority_score'],
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('category', models.CharField(choices=[('accident', 'Accident'), ('hazard', 'Hazard'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], max_length=50, verbose_name='category')),
                ('severity_template', models.CharField(default='P3', max_length=10, verbose_name='default severity')),
                ('default_sla_minutes', models.IntegerField(default=60, verbose_name='default SLA minutes')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'incident type',
                'verbose_name_plural': 'incident types',
                'db_table': 'incident_types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IncidentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='message')),
                ('message_type', models.CharField(choices=[('chat', 'Chat'), ('follow_up', 'Follow-up'), ('request', 'Request')], default='chat', max_length=20, verbose_name='message type')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'incident message',
                'verbose_name_plural': 'incident messages',
                'db_table': 'incident_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
