# Generated by Django 4.2.7 on 2025-10-31 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentcomment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incidentcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='incidents.incidentcomment'),
        ),
        migrations.AddField(
            model_name='incidentcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.incidenttype'),
        ),
        migrations.AddField(
            model_name='incident',
            name='parent_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_incidents', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.incidentseverity'),
        ),
        migrations.AddField(
            model_name='incident',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'severity'], name='incidents_status_5e2414_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['verification_status', 'ai_confidence_score'], name='incidents_verific_dcbf39_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['created_at'], name='incidents_created_bc994b_idx'),
        ),
    ]
