# Generated by Django 4.2.7 on 2025-10-31 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('inspection', 'Inspection'), ('repair', 'Repair'), ('maintenance', 'Maintenance')], max_length=20, verbose_name='work type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('priority', models.CharField(default='medium', max_length=20, verbose_name='priority')),
                ('description', models.TextField(verbose_name='description')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('estimated_duration', models.IntegerField(blank=True, null=True, verbose_name='estimated duration (minutes)')),
                ('actual_duration', models.IntegerField(blank=True, null=True, verbose_name='actual duration (minutes)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('completion_notes', models.TextField(blank=True, verbose_name='completion notes')),
                ('media_attachments', models.JSONField(blank=True, default=list, verbose_name='media attachments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'work order',
                'verbose_name_plural': 'work orders',
                'db_table': 'work_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfrastructureInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(verbose_name='inspection date')),
                ('inspection_type', models.CharField(max_length=50, verbose_name='inspection type')),
                ('damage_assessment', models.JSONField(blank=True, default=dict, verbose_name='damage assessment')),
                ('repair_needed', models.BooleanField(default=False, verbose_name='repair needed')),
                ('priority', models.CharField(default='medium', max_length=20, verbose_name='priority')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='photos')),
                ('inspection_report', models.TextField(blank=True, verbose_name='inspection report')),
                ('blockchain_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='blockchain hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='workorders.workorder')),
            ],
            options={
                'verbose_name': 'infrastructure inspection',
                'verbose_name_plural': 'infrastructure inspections',
                'db_table': 'infrastructure_inspections',
            },
        ),
    ]
