# Generated by Django 4.2.7 on 2025-10-31 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio')], max_length=20, verbose_name='asset type')),
                ('file_path', models.URLField(max_length=500, verbose_name='file path')),
                ('file_hash', models.CharField(db_index=True, max_length=64, verbose_name='file hash (SHA256)')),
                ('file_size', models.BigIntegerField(verbose_name='file size (bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME type')),
                ('thumbnail_path', models.URLField(blank=True, max_length=500, verbose_name='thumbnail path')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('compression_applied', models.BooleanField(default=False, verbose_name='compression applied')),
                ('exif_scrubbed', models.BooleanField(default=False, verbose_name='EXIF scrubbed')),
                ('geotag_removed', models.BooleanField(default=False, verbose_name='geotag removed')),
                ('faces_redacted', models.BooleanField(default=False, verbose_name='faces redacted')),
                ('license_plates_redacted', models.BooleanField(default=False, verbose_name='license plates redacted')),
                ('redaction_config', models.JSONField(blank=True, default=dict, verbose_name='redaction config')),
                ('virus_scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected')], default='pending', max_length=20, verbose_name='virus scan status')),
                ('virus_scan_result', models.TextField(blank=True, verbose_name='virus scan result')),
                ('blockchain_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='blockchain hash')),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='blockchain transaction hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'media asset',
                'verbose_name_plural': 'media assets',
                'db_table': 'media_assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
