# Generated by Django 4.2.7 on 2025-10-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50, verbose_name='transaction type')),
                ('entity_type', models.CharField(max_length=50, verbose_name='entity type')),
                ('entity_id', models.CharField(max_length=100, verbose_name='entity ID')),
                ('transaction_hash', models.CharField(max_length=66, unique=True, verbose_name='transaction hash')),
                ('block_number', models.BigIntegerField(blank=True, null=True, verbose_name='block number')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
    ]
