# Generated by Django 4.2.7 on 2025-10-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('rfid', 'RFID'), ('cctv', 'CCTV'), ('sensor', 'Sensor'), ('mapping', 'Mapping'), ('sms', 'SMS'), ('email', 'Email'), ('blockchain', 'Blockchain')], max_length=20, verbose_name='integration type')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('configuration', models.JSONField(default=dict, help_text='API keys, endpoints, credentials (encrypted)', verbose_name='configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='last sync at')),
                ('sync_status', models.CharField(default='unknown', max_length=20, verbose_name='sync status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'integration configuration',
                'verbose_name_plural': 'integration configurations',
                'db_table': 'integration_configurations',
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='key')),
                ('value', models.TextField(verbose_name='value')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20, verbose_name='value type')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='category')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_editable', models.BooleanField(default=True, verbose_name='is editable')),
                ('requires_restart', models.BooleanField(default=False, verbose_name='requires restart')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'system configuration',
                'verbose_name_plural': 'system configurations',
                'db_table': 'system_configurations',
            },
        ),
    ]
